packages:
  - "apps/*"
  - "packages/*"
overrides:
  '@simple-git/argv-parser': 2.0.1
allowBuilds:
  electron-winstaller: true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
  tree-sitter: true
